# Site settings
title: adamspe.github.io
email: adamspe@gmail.com
email1: adamspe@notiosoftware.com
ext_site: "http://notiosoftware.com"
description: > # this means to ignore newlines until "baseurl:"
  Notio Software LLC is my small (as in me) software consulting
  company.  Some of my projects, mostly learning/examples, I'm hosting
  in the github repos.  It's an amazing tool/community for sharing open
  source software and knowledge in general.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamspe.github.io" # the base hostname & protocol for your site
twitter_username: adamspe38
github_username:  adamspe

# Build settings
markdown: kramdown
